name: Run Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip

          pip install -r requirements.txt
          pip install pytest

      - name: DVC
        shell: bash
        env:
          MINIO_ENDPOINT_URL: ${{ secrets.MINIO_ENDPOINT_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          set -euo pipefail

          dvc remote list | grep -E '^minio\s' || (echo "Remote 'minio' not found. Check .dvc/config" && exit 1)
          dvc remote modify --local minio endpointurl "${MINIO_ENDPOINT_URL}"
          dvc remote modify --local minio use_ssl false
          dvc pull -v data/processed/passages.jsonl data/processed/retriever_train.jsonl data/processed/retriever_valid.jsonl artifacts/retriever_ru artifacts/passages_index.pkl

      - name: Run tests
        shell: bash
        run: |
          set -euo pipefail
          pytest -q
